steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_DEPLOY_REGION}-docker.pkg.dev/${PROJECT_ID}/vloader/v-server-prod",
        ".",
      ]
    env: "DOCKER_BUILDKIT=1"
